name: CI

on: 
  push:
    branches:
    - main
    
jobs:
  clean_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get
    
    
