name: CI

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  clean_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@2783a3f08e1baf891508463f8c6653c258246225
        uses: subosito/flutter-action@v2.12.0
        with:
          # The Flutter version to make available on the path
          flutter-version: 3.13.9
          # The Flutter build release channel
          channel: 'stable'
          # Cache the Flutter SDK
          cache: true
          # Optional identifier for the Flutter SDK cache
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          # Optional Flutter SDK cache path
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
          # Optional, change this to force refresh cache of dart pub get dependencies
          # pub-cache-key: 'flutter-pub:os:-:channel:-:version:-:arch:-:hash:'
          # Optional, change this to specify the cache path 
          #pub-cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Run tests
        run: flutter test
    
    
