name: CI

on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    
jobs:
  clean_workspace:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Flutter
        uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
          
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Flutter clean
        run: flutter clean

      - name: Flutter pub get
        run: flutter pub get

      - name: Run tests
        run: flutter test
    
    
